#pragma once

#define ot_rate_auto_deinit hi_rate_auto_deinit
#define ot_rate_auto_init hi_rate_auto_init
#define ot_rate_auto_load_param hi_rate_auto_load_param

#define ss_mpi_ae_register hi_mpi_ae_register
#define ss_mpi_ae_unregister hi_mpi_ae_unregister

#define ss_mpi_ai3dnr_disable hi_mpi_ai3dnr_disable
#define ss_mpi_ai3dnr_enable hi_mpi_ai3dnr_enable
#define ss_mpi_ai3dnr_exit hi_mpi_ai3dnr_exit
#define ss_mpi_ai3dnr_init hi_mpi_ai3dnr_init
#define ss_mpi_ai3dnr_load_model hi_mpi_ai3dnr_load_model
#define ss_mpi_ai3dnr_unload_model hi_mpi_ai3dnr_unload_model

#define ss_mpi_aibnr_disable hi_mpi_aibnr_disable
#define ss_mpi_aibnr_enable hi_mpi_aibnr_enable
#define ss_mpi_aibnr_exit hi_mpi_aibnr_exit
#define ss_mpi_aibnr_get_attr hi_mpi_aibnr_get_attr
#define ss_mpi_aibnr_init hi_mpi_aibnr_init
#define ss_mpi_aibnr_load_model hi_mpi_aibnr_load_model
#define ss_mpi_aibnr_set_attr hi_mpi_aibnr_set_attr
#define ss_mpi_aibnr_unload_model hi_mpi_aibnr_unload_model

#define ss_mpi_aidrc_disable hi_mpi_aidrc_disable
#define ss_mpi_aidrc_enable hi_mpi_aidrc_enable
#define ss_mpi_aidrc_exit hi_mpi_aidrc_exit
#define ss_mpi_aidrc_get_attr hi_mpi_aidrc_get_attr
#define ss_mpi_aidrc_init hi_mpi_aidrc_init
#define ss_mpi_aidrc_load_model hi_mpi_aidrc_load_model
#define ss_mpi_aidrc_set_attr hi_mpi_aidrc_set_attr
#define ss_mpi_aidrc_unload_model hi_mpi_aidrc_unload_model

#define ss_mpi_awb_register hi_mpi_awb_register
#define ss_mpi_awb_unregister hi_mpi_awb_unregister

#define ss_mpi_isp_exit hi_mpi_isp_exit
#define ss_mpi_isp_get_exposure_attr hi_mpi_isp_get_exposure_attr
#define ss_mpi_isp_init hi_mpi_isp_init
#define ss_mpi_isp_mem_init hi_mpi_isp_mem_init
#define ss_mpi_isp_query_exposure_info hi_mpi_isp_query_exposure_info
#define ss_mpi_isp_run hi_mpi_isp_run
#define ss_mpi_isp_set_pub_attr hi_mpi_isp_set_pub_attr

#define ss_mpi_rgn_attach_to_chn hi_mpi_rgn_attach_to_chn
#define ss_mpi_rgn_create hi_mpi_rgn_create
#define ss_mpi_rgn_destroy hi_mpi_rgn_destroy
#define ss_mpi_rgn_detach_from_chn hi_mpi_rgn_detach_from_chn
#define ss_mpi_rgn_get_canvas_info hi_mpi_rgn_get_canvas_info
#define ss_mpi_rgn_update_canvas hi_mpi_rgn_update_canvas

#define ss_mpi_sys_bind hi_mpi_sys_bind
#define ss_mpi_sys_exit hi_mpi_sys_exit
#define ss_mpi_sys_init hi_mpi_sys_init
#define ss_mpi_sys_mmap hi_mpi_sys_mmap
#define ss_mpi_sys_mmz_alloc hi_mpi_sys_mmz_alloc
#define ss_mpi_sys_mmz_free hi_mpi_sys_mmz_free
#define ss_mpi_sys_munmap hi_mpi_sys_munmap
#define ss_mpi_sys_set_3dnr_pos hi_mpi_sys_set_3dnr_pos
#define ss_mpi_sys_set_vi_aiisp_mode hi_mpi_sys_set_vi_aiisp_mode
#define ss_mpi_sys_set_vi_vpss_mode hi_mpi_sys_set_vi_vpss_mode
#define ss_mpi_sys_unbind hi_mpi_sys_unbind

#define ss_mpi_vb_create_pool hi_mpi_vb_create_pool
#define ss_mpi_vb_destroy_pool hi_mpi_vb_destroy_pool
#define ss_mpi_vb_exit hi_mpi_vb_exit
#define ss_mpi_vb_exit_mod_common_pool hi_mpi_vb_exit_mod_common_pool
#define ss_mpi_vb_get_pool_info hi_mpi_vb_get_pool_info
#define ss_mpi_vb_init hi_mpi_vb_init
#define ss_mpi_vb_pool_share_all hi_mpi_vb_pool_share_all
#define ss_mpi_vb_set_cfg hi_mpi_vb_set_cfg
#define ss_mpi_vb_set_supplement_cfg hi_mpi_vb_set_supplement_cfg

#define ss_mpi_venc_create_chn hi_mpi_venc_create_chn
#define ss_mpi_venc_destroy_chn hi_mpi_venc_destroy_chn
#define ss_mpi_venc_get_fd hi_mpi_venc_get_fd
#define ss_mpi_venc_get_jpeg_param hi_mpi_venc_get_jpeg_param
#define ss_mpi_venc_get_stream hi_mpi_venc_get_stream
#define ss_mpi_venc_query_status hi_mpi_venc_query_status
#define ss_mpi_venc_release_stream hi_mpi_venc_release_stream
#define ss_mpi_venc_request_idr hi_mpi_venc_request_idr
#define ss_mpi_venc_send_frame hi_mpi_venc_send_frame
#define ss_mpi_venc_set_jpeg_param hi_mpi_venc_set_jpeg_param
#define ss_mpi_venc_start_chn hi_mpi_venc_start_chn
#define ss_mpi_venc_stop_chn hi_mpi_venc_stop_chn

#define ss_mpi_vgs_add_cover_task hi_mpi_vgs_add_cover_task
#define ss_mpi_vgs_add_osd_task hi_mpi_vgs_add_osd_task
#define ss_mpi_vgs_begin_job hi_mpi_vgs_begin_job
#define ss_mpi_vgs_end_job hi_mpi_vgs_end_job

#define ss_mpi_vi_attach_aiisp_vb_pool hi_mpi_vi_attach_aiisp_vb_pool
#define ss_mpi_vi_bind hi_mpi_vi_bind
#define ss_mpi_vi_create_pipe hi_mpi_vi_create_pipe
#define ss_mpi_vi_destroy_pipe hi_mpi_vi_destroy_pipe
#define ss_mpi_vi_detach_aiisp_vb_pool hi_mpi_vi_detach_aiisp_vb_pool
#define ss_mpi_vi_disable_chn hi_mpi_vi_disable_chn
#define ss_mpi_vi_disable_dev hi_mpi_vi_disable_dev
#define ss_mpi_vi_enable_chn hi_mpi_vi_enable_chn
#define ss_mpi_vi_enable_dev hi_mpi_vi_enable_dev
#define ss_mpi_vi_set_chn_attr hi_mpi_vi_set_chn_attr
#define ss_mpi_vi_set_dev_attr hi_mpi_vi_set_dev_attr
#define ss_mpi_vi_set_pipe_3dnr_attr hi_mpi_vi_set_pipe_3dnr_attr
#define ss_mpi_vi_set_wdr_fusion_grp_attr hi_mpi_vi_set_wdr_fusion_grp_attr
#define ss_mpi_vi_start_pipe hi_mpi_vi_start_pipe
#define ss_mpi_vi_stop_pipe hi_mpi_vi_stop_pipe
#define ss_mpi_vi_unbind hi_mpi_vi_unbind

#define ss_mpi_vo_disable hi_mpi_vo_disable
#define ss_mpi_vo_disable_chn hi_mpi_vo_disable_chn
#define ss_mpi_vo_disable_video_layer hi_mpi_vo_disable_video_layer
#define ss_mpi_vo_enable hi_mpi_vo_enable
#define ss_mpi_vo_enable_chn hi_mpi_vo_enable_chn
#define ss_mpi_vo_enable_video_layer hi_mpi_vo_enable_video_layer
#define ss_mpi_vo_set_chn_attr hi_mpi_vo_set_chn_attr
#define ss_mpi_vo_set_pub_attr hi_mpi_vo_set_pub_attr
#define ss_mpi_vo_set_video_layer_attr hi_mpi_vo_set_video_layer_attr

#define ss_mpi_vpss_attach_chn_vb_pool hi_mpi_vpss_attach_chn_vb_pool
#define ss_mpi_vpss_create_grp hi_mpi_vpss_create_grp
#define ss_mpi_vpss_destroy_grp hi_mpi_vpss_destroy_grp
#define ss_mpi_vpss_disable_chn hi_mpi_vpss_disable_chn
#define ss_mpi_vpss_enable_chn hi_mpi_vpss_enable_chn
#define ss_mpi_vpss_get_chn_frame hi_mpi_vpss_get_chn_frame
#define ss_mpi_vpss_get_grp_frame hi_mpi_vpss_get_grp_frame
#define ss_mpi_vpss_release_chn_frame hi_mpi_vpss_release_chn_frame
#define ss_mpi_vpss_release_grp_frame hi_mpi_vpss_release_grp_frame
#define ss_mpi_vpss_set_chn_attr hi_mpi_vpss_set_chn_attr
#define ss_mpi_vpss_set_chn_low_delay hi_mpi_vpss_set_chn_low_delay
#define ss_mpi_vpss_set_chn_vb_src hi_mpi_vpss_set_chn_vb_src
#define ss_mpi_vpss_start_grp hi_mpi_vpss_start_grp
#define ss_mpi_vpss_stop_grp hi_mpi_vpss_stop_grp
